### ISSUE TITLE
delete implementation

### ISSUE THREAD

**Issue by mccreadylemon** [xbenjii/Prestan#7] opened 2015-11-09 18:40 UTC
Hello,
is delete implemented?
I get 
[TypeError: Object function request(uri, options, callback) {
  if (typeof uri === 'undefined') {
    throw new Error('undefined is not a valid uri or options object.')
  }

  var params = initParams(uri, options, callback)

  if (params.method === 'HEAD' && paramsHaveRequestBody(params)) {
    throw new Error('HTTP HEAD requests MUST NOT include a request body.')
  }

  return new request.Request(params)
} has no method 'delete']

**Comment by mccreadylemon** [comment] 2015-11-09 18:50
also here is my code

  prestan.delete('addresses', {id:3} ).then(function(response){
            console.log(response);
            }).catch(function(error) {
            console.log(error);
        });

**Comment by xbenjii** [comment] 2015-11-11 00:27
Delete is implemented yes, can you post the full code snippet you're using?

**Comment by mccreadylemon** [comment] 2015-11-11 10:02
is the above syntax correct?
thanks

**Comment by xbenjii** [comment] 2015-11-11 16:09
The code looks correct, but can you post the code you're using to require and instantiate the library?

**Comment by mccreadylemon** [comment] 2015-11-11 16:28
var config = require('./config'),
    Prestan = require('prestan'),
    options = {debug: config.production ? false : true},
    prestan = new Prestan(config.remoteUrl, config._API_KEY_ , options);

module.exports = prestan;

**Comment by mccreadylemon** [comment] 2015-11-13 22:01
any update?

**Comment by xbenjii** [comment] 2015-11-13 23:19
Can't reproduce it, sorry.

**Comment by liferus** [comment] 2016-02-29 17:29
node_modules/prestan/index.js
line #177: `return this.executeRequest('delete', url).then(function (response) {`
replace: `return this.executeRequest('del', url).then(function (response) {`

**Comment by xbenjii** [comment] 2016-02-29 17:36
@liferus That's wrong.  Closing this anyway.

**Closed as completed by xbenjii** 2016-02-29 17:36 UTC

**Comment by mccreadylemon** [comment] 2016-03-13 16:34
actually that worked! thanks!
